---
- id: ansible-lint
  name: Ansible-lint
  description: This hook runs ansible-lint.
  entry: python3 -m ansiblelint -v --force-color
  language: python
  pass_filenames: false
  always_run: true
  additional_dependencies:
    - ansible-core>=2.13.3
