---
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.4"
  - name: kubernetes.core
    version: ">=2.4.0"
