---
- name: Run always
  tags: [always]
  block:
    - name: Check if there is group named masters
      ansible.builtin.assert:
        that: "'masters' in groups"
        msg: "There must be a group named masters"
        quiet: true
      delegate_to: localhost

    - name: Check if there is group named workers
      ansible.builtin.assert:
        that: "'workers' in groups"
        msg: "There must be a group named workers"
        quiet: true
      delegate_to: localhost

    - name: Check if the masters group has only one host
      ansible.builtin.assert:
        that: "groups['masters'] | length == 1"
        msg: "The master group must have only one host"
        quiet: true
      delegate_to: localhost

    - name: Check if the workers group has at least one host
      ansible.builtin.assert:
        that: "groups['workers'] | length > 0"
        msg: "The worker group must have at least one host"
        quiet: true
      delegate_to: localhost

    - name: Set amd64 if x86_64 else ansible_architecture
      ansible.builtin.set_fact:
        arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
      delegate_to: localhost
