---
- name: Site Playbook
  hosts: all
  become: true
  roles:
    - role: containerd
    - role: kubernetes

- name: Master specific tasks
  hosts: masters
  become: true
  roles:
    - role: kubectl
      tags: [kubectl]

    - role: k8s_network
      tags: [network]

    - role: argocd
      tags: [argocd]
      when: argocd_enabled | default(false) | bool

    - role: metallb
      tags: [metallb]
      when: metallb_enabled | default(false) | bool
