---
- name: Import playbook_setup_instances
  ansible.builtin.import_playbook: playbook_setup_instances.yaml

- name: Import playbook_kubeadm
  ansible.builtin.import_playbook: playbook_kubeadm.yaml

- name: Import playbook_post_install
  ansible.builtin.import_playbook: playbook_post_install.yaml
