---
- name: Import playbook_all
  ansible.builtin.import_playbook: playbook_all.yaml

- name: Import playbook_masters
  ansible.builtin.import_playbook: playbook_masters.yaml

- name: Import playbook_workers
  ansible.builtin.import_playbook: playbook_workers.yaml

- name: Import playbook_masters_addons
  ansible.builtin.import_playbook: playbook_masters_addons.yaml
