---
- name: Include master.yaml when hostname is group master
  ansible.builtin.include_tasks: masters.yaml
  when: inventory_hostname in groups['masters']

- name: Include workers.yaml when hostname is group workers
  ansible.builtin.include_tasks: workers.yaml
  when: inventory_hostname in groups['workers']
