---
all:
  vars:
    ansible_user: ubuntu
    kubernetes_cni: flannel
    kubernetes_argocd_install: true
    metallb_enabled: true
    metallb_ip_range: "10.100.200.80-10.100.200.89"
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.100.200.2
    workers:
      hosts:
        node01:
          ansible_host: 10.100.200.3
        node02:
          ansible_host: 10.100.200.4
