---
all:
  vars:
    ansible_user: ubuntu
    kube_network_cni: flannel
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.100.200.10
    workers:
      hosts:
        node1:
          ansible_host: 10.100.200.11
        node2:
          ansible_host: 10.100.200.12
