---
all:
  vars:
    ansible_user: ubuntu
    kubernetes_cni: flannel
    kubernetes_argocd_install: true
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.100.200.2
    nodes:
      hosts:
        node01:
          ansible_host: 10.100.200.3
        node02:
          ansible_host: 10.100.200.4
