---
all:
  vars:
    ansible_user: ubuntu
    cluster_name: k8s
    cluster_domain: local
    cluster_service_subnet: 10.96.0.0/12
    cluster_pod_subnet: 10.244.0.0/16
    cluster_cni: flannel
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.100.200.10
    workers:
      hosts:
        node1:
          ansible_host: 10.100.200.11
        node2:
          ansible_host: 10.100.200.12
