---
- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: openebs_temp_dir
  changed_when: false

- name: Copy template for OpenEBS CStor operator
  ansible.builtin.template:
    src: cstor-operator.yaml.j2
    dest: "{{ openebs_temp_dir.path }}/cstor-operator.yaml"
    mode: "0555"
  changed_when: false

- name: Deploy OpenEBS CStor pool
  kubernetes.core.k8s:
    state: present
    src: "{{ openebs_temp_dir.path }}/cstor-operator.yaml"
    wait: true

- name: Get block device infos
  kubernetes.core.k8s_info:
    api_version: openebs.io/v1alpha1
    kind: BlockDevice
    namespace: "{{ openebs_namespace }}"
  register: block_device_info

- name: Copy template for OpenEBS CStor pool
  ansible.builtin.template:
    src: cstor-pool.yaml.j2
    dest: "{{ openebs_temp_dir.path }}/cstor-pool.yaml"
    mode: "0555"
  changed_when: false

- name: Deploy OpenEBS CStor pool
  kubernetes.core.k8s:
    state: present
    src: "{{ openebs_temp_dir.path }}/cstor-pool.yaml"
    wait: true

- name: Remove temporary files
  ansible.builtin.file:
    path: "{{ openebs_temp_dir.path }}"
    state: absent
  changed_when: false
