---
- name: Download MetalLB
  ansible.builtin.get_url:
    url: "{{ metallb_url }}"
    dest: "{{ metallb_temp_file }}"
    mode: "0664"

- name: Apply MetalLB
  kubernetes.core.k8s:
    state: present
    src: "{{ metallb_temp_file }}"

- name: Configure MetalLB IP Pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ metallb_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        addresses:
          - "{{ metallb_ip_pool }}"
  register: metallb_ip_pool_result
  until: metallb_ip_pool_result is success
  retries: 5
  delay: 20

- name: Purge MetalLB temporary file
  ansible.builtin.file:
    path: "{{ metallb_temp_file }}"
    state: absent

- name: Configure MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: "{{ metallb_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        ipaddresspools:
          - "{{ metallb_name }}"
        interfaces:
          - "{{ metallb_interface }}"
  register: metallb_l2advertisement_result
  until: metallb_l2advertisement_result is success
  retries: 5
  delay: 20
