---
- name: Add MetalLB namespace
  kubernetes.core.k8s:
    name: "{{ metallb_namespace }}"
    api_version: v1
    kind: Namespace
    state: present


- name: Install MetalLB
  kubernetes.core.helm:
    name: "{{ metallb_name }}"
    chart_ref: metallb
    chart_repo_url: "{{ metallb_helm_url }}"
    chart_version: "{{ metallb_version }}"
    release_namespace: "{{ metallb_namespace }}"
    state: present

- name: Configure MetalLB IP Pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ metallb_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        addresses:
          - "{{ metallb_ip_range }}"
  register: metallb_ip_range_result
  until: metallb_ip_range_result is success
  retries: 5
  delay: 20

- name: Configure MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: "{{ metallb_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        ipAddressPools:
          - "{{ metallb_name }}"
  register: metallb_l2advertisement_result
  until: metallb_l2advertisement_result is success
  retries: 5
  delay: 20
