---
- name: Download calico
  ansible.builtin.get_url:
    url: "{{ k8s_network_calico_url }}"
    dest: /tmp/calico.yaml
    mode: '0664'

- name: Apply calico
  kubernetes.core.k8s:
    state: present
    src: /tmp/calico.yaml

- name: Purge temporary calico file
  ansible.builtin.file:
    path: /tmp/calico.yaml
    state: absent
