---
- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    state: present
    name: argocd
    kind: Namespace

- name: Download ArgoCD
  ansible.builtin.get_url:
    url: "{{ argocd_url }}"
    dest: "{{ argocd_temp_file }}"
    mode: '0664'

- name: Apply ArgoCD
  kubernetes.core.k8s:
    state: present
    src: "{{ argocd_temp_file }}"
    namespace: argocd

- name: Install ArgoCD cli
  ansible.builtin.get_url:
    url: "{{ argocd_cli_url }}"
    dest: /usr/local/bin/argocd
    mode: '0555'

- name: Purge ArgoCD temp file
  ansible.builtin.file:
    path: "{{ argocd_temp_file }}"
    state: absent
