---
- name: List certificates requests on kubernetes
  kubernetes.core.k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
  register: csr_list

- name: Approve certificates requests
  ansible.builtin.command:
    cmd: kubectl certificate approve {{ item }}
  loop: "{{ csr_list | default({}) | community.general.json_query('resources[?length(status)==`0`].metadata.name') }}"  # yamllint disable-line
  register: csr_approve
  changed_when: csr_approve.stdout != ""
