---
- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: kubeseal_temp_dir
  changed_when: false

- name: Install sealed-secrets Helm chart
  kubernetes.core.helm:
    name: "{{ kubeseal_name }}"
    chart_ref: sealed-secrets
    chart_repo_url: "{{ kubeseal_repo_url }}"
    chart_version: "{{ kubeseal_version }}"
    release_namespace: "{{ kubeseal_namespace }}"
    state: present
    wait: true

- name: Download Kubeseal CLI
  ansible.builtin.get_url:
    url: "{{ kubeseal_cli_url }}"
    dest: "{{ kubeseal_temp_dir.path }}/{{ kubeseal_cli_temp_file }}"
    mode: "0555"
  changed_when: false

- name: Uncompress Kubeseal CLI
  ansible.builtin.unarchive:
    src: "{{ kubeseal_temp_dir.path }}/{{ kubeseal_cli_temp_file }}"
    dest: "{{ kubeseal_temp_dir.path }}"
    remote_src: true
    mode: "0555"
  changed_when: false

- name: Move Kubeseal CLI to bin path
  ansible.builtin.copy:
    src: "{{ kubeseal_temp_dir.path }}/kubeseal"
    dest: "{{ kubeseal_cli_bin_path }}"
    remote_src: true
    mode: "0555"

- name: Remove temporary files
  ansible.builtin.file:
    path: "{{ kubeseal_temp_dir.path }}"
    state: absent
  changed_when: false
