---
kubeadm_cluster_name: "{{ cluster_name | default('cluster') }}"
kubeadm_cluster_domain: "{{ cluster_domain | default('local') }}"
kubeadm_skip_kubeproxy: false
kubeadm_service_subnet: "{{ cluster_service_subnet | default('10.96.0.0/12') }}"
kubeadm_pod_subnet: "{{ cluster_pod_subnet | default('10.244.0.0/16') }}"
kubeadm_dns_domain: "{{ kubeadm_cluster_name }}.{{ kubeadm_cluster_domain }}"
kubeadm_join_command_file: /tmp/kubeadm_join_command.yaml
