---
- name: Copy kubeadm-config
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
    mode: '0644'

- name: Initialize Kubernetes Cluster
  ansible.builtin.command:
    cmd: kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  failed_when: kubeadm_init.rc != 0
  changed_when: kubeadm_init.rc == 0
    and kubeadm_init.stdout.find('skipped') == -1
