---
- name: Check if Cilium ingress is enabled and kube-proxy is replaced
  ansible.builtin.fail:
    msg: |
      When using Cilium ingress, kube-proxy must be replaced by Cilium.
      Please set kube_network_cilium_ingress_enabled and kube_network_cilium_kubeproxy_replacement to true.
      kube_network_cilium_gateway_api_enabled must be set to false.
  when: kube_network_cilium_ingress_enabled and (not kube_network_cilium_kubeproxy_replacement or kube_network_cilium_gateway_api_enabled)

- name: Check if Cilium gateway API is enabled and kube-proxy is replaced
  ansible.builtin.fail:
    msg: |
      When using Cilium gateway API, kube-proxy must be replaced by Cilium.
      Please set kube_network_cilium_gateway_api_enabled and kube_network_cilium_kubeproxy_replacement to true.
      kube_network_cilium_ingress_enabled must be set to false.
  when: kube_network_cilium_gateway_api_enabled and (not kube_network_cilium_kubeproxy_replacement or kube_network_cilium_ingress_enabled)

- name: Download Gateway API CRDs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ kube_network_temp_dir.path }}/{{ item.name }}"
    mode: "0555"
  loop: "{{ kube_network_cilium_gateway_api_crds_urls }}"
  loop_control:
    label: "{{ item.name }}"
  changed_when: false
  when: kube_network_cilium_gateway_api_enabled

- name: Apply Gateway API CRDs manifests
  kubernetes.core.k8s:
    src: "{{ kube_network_temp_dir.path }}/{{ item.name }}"
    state: present
  loop: "{{ kube_network_cilium_gateway_api_crds_urls }}"
  loop_control:
    label: "{{ item.name }}"
  when: kube_network_cilium_gateway_api_enabled

- name: Download Cilium CLI
  ansible.builtin.get_url:
    url: "{{ kube_network_cilium_cli_url }}"
    dest: "{{ kube_network_temp_dir.path }}/{{ kube_network_cilium_cli_temp_file }}"
    mode: "0555"
  changed_when: false

- name: Download Cilium CLI checksum
  ansible.builtin.get_url:
    url: "{{ kube_network_cilium_cli_sha256_url }}"
    dest: "{{ kube_network_temp_dir.path }}/{{ kube_network_cilium_cli_temp_file }}.sha256"
    mode: "0555"
  changed_when: false

- name: Use sha256 to calculate the checksum
  ansible.builtin.stat:
    path: "{{ kube_network_temp_dir.path }}/{{ kube_network_cilium_cli_temp_file }}"
    checksum_algorithm: sha256
  register: kube_network_cilium_cli_sha256_stat

- name: Get the checksum from the file
  ansible.builtin.slurp:
    path: "{{ kube_network_temp_dir.path }}/{{ kube_network_cilium_cli_temp_file }}.sha256"
  register: kube_network_cilium_cli_sha256_slurp

- name: Check if the checksum is correct
  ansible.builtin.fail:
    msg: Checksum of {{ kube_network_cilium_cli_temp_file }} is not correct
  when: kube_network_cilium_cli_sha256_stat.stat.checksum != kube_network_cilium_cli_sha256_slurp.content | b64decode | split(' ') | first

- name: Uncompress Cilium CLI
  ansible.builtin.unarchive:
    src: "{{ kube_network_temp_dir.path }}/{{ kube_network_cilium_cli_temp_file }}"
    dest: "{{ kube_network_temp_dir.path }}"
    remote_src: true
    mode: "0555"
  changed_when: false

- name: Move Cilium CLI to bin path
  ansible.builtin.copy:
    src: "{{ kube_network_temp_dir.path }}/cilium"
    dest: "{{ kube_network_cilium_cli_bin_path }}"
    remote_src: true
    mode: "0555"

- name: Install Cilium bash completion
  ansible.builtin.shell:
    cmd: "{{ kube_network_cilium_cli_bin_path }} completion bash > {{ kube_network_cilium_cli_bash_completion_path }}"
    creates: "{{ kube_network_cilium_cli_bash_completion_path }}"

- name: Template for Cilium Helm chart
  ansible.builtin.template:
    src: cilium-values.yaml.j2
    dest: "{{ kube_network_temp_dir.path }}/cilium-values.yaml"
    mode: "0555"

# Reference of values: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
- name: Install Cilium Helm chart
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: "{{ kube_network_cilium_helm_repo }}"
    chart_version: "{{ kube_network_cilium_version }}"
    release_namespace: kube-system
    values_files:
      - "{{ kube_network_temp_dir.path }}/cilium-values.yaml"
    state: present
    wait: true
