---
- name: Download flannel
  ansible.builtin.get_url:
    url: "{{ k8s_network_flannel_url }}"
    dest: /tmp/flannel.yaml
    mode: '0664'

- name: Apply flannel
  kubernetes.core.k8s:
    state: present
    src: /tmp/flannel.yaml

- name: Purge temporary flannel file
  ansible.builtin.file:
    path: /tmp/flannel.yaml
    state: absent
