---
argocd_enabled: false
argocd_namespace: argocd
argocd_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
argocd_cli_url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
argocd_cli_bin_path: /usr/local/bin/argocd
argocd_api_version: argoproj.io/v1alpha1
argocd_timeout_reconciliation: 180s
argocd_main_app_name: guestbook
argocd_main_app_namespace: argocd
argocd_main_app_repo_url: https://github.com/argoproj/argocd-example-apps.git
argocd_main_app_repo_path: guestbook
argocd_main_app_repo_branch: HEAD
argocd_main_app_repo_private: false
argocd_main_app_repo_username: ""
argocd_main_app_repo_password: ""
argocd_main_app_destination_server: https://kubernetes.default.svc
argocd_main_app_destination_namespace: default
