---
all:
  vars:
    ansible_user: dyego
    cluster_name: k8s
    cluster_domain: nodes.ee
    cluster_service_subnet: 10.85.0.0/16
    cluster_pod_subnet: 10.86.0.0/16
    cluster_schedule_on_master: true
    cluster_cni: cilium
    kubeadm_skip_kubeproxy: true
    kube_network_cilium_kubeproxy_replacement: true
    kube_network_cilium_gateway_api_enabled: true
    kube_network_cilium_hubble_enabled: true
    kube_network_cilium_hubble_relay_enabled: true
    kube_network_cilium_hubble_ui_enabled: true
  children:
    masters:
      hosts:
        node1:
          ansible_host: 172.31.85.10
    workers:
