---
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible-Galaxy Requirements
        run: ansible-galaxy install --force -r requirements.yaml
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Python Requirements
        run: pip install -r requirements.txt
      - name: Retrieve ansible-lint requirements
        run: wget --output-document=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
      - name: Install ansible-lint requirements
        run: pip install -r .git/ansible-lint-requirements.txt
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.21.1
        with:
          setup_python: false
