---
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible-Galaxy Requirements
        run: ansible-galaxy install --force -r requirements.yaml
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.3
